name: DocC

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'glib glib-networking gobject-introspection pkg-config jq' }}

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docc:
    name: Generate Documentation
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: SwiftGLib

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Swift version
        run: swift --version

      - name: Fetch macOS dependencies
        run: |
          brew install python@3 || brew link --overwrite python@3
          brew install $MACOS_BREW
          mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.orig || sudo mv /Library/Developer/CommandLineTools /Library/Developer/CommandLineTools.orig

      - name: Generate Documentation
        run: |
          cd SwiftGLib
          swift package \
            --allow-writing-to-directory ../docs \
            generate-documentation \
            --output-path ../docs \
            --transform-for-static-hosting \
            --hosting-base-path ${{ github.event.repository.name }}

      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy-docc:
    name: Deploy Documentation
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docc
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
